# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Drug vs Disease
tagline:          An R and Cytoscape plug-in for comparing Drug and Disease profiles
description:      "An R and Cytoscape plug-in for comparing Drug and Disease profiles"
#url:              https://github.com/saezlab/DrugVsDisease
baseurl:          /DrugVsDisease/
toollogo:         /DrugVsDisease/tool_logo.png

author:
  name:           'C. Pacini'

paginate:         5

# Custom vars
version:          3.4

github:
  repo:           https://github.com/saezlab/DrugVsDisease
